jueves/config/routes.rb
Rails.application.routes.draw do
  resources :personas
  resources :apartamentos
  resources :torres
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

jueves/app/models/apartamento.rb
class Apartamento < ApplicationRecord
end

jueves/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

jueves/app/models/persona.rb
class Persona < ApplicationRecord
end

jueves/app/models/torre.rb
class Torre < ApplicationRecord
end

jueves/app/controllers/apartamentos_controller.rb
class ApartamentosController < ApplicationController
  before_action :set_apartamento, only: [:show, :edit, :update, :destroy]

  # GET /apartamentos
  # GET /apartamentos.json
  def index
    @apartamentos = Apartamento.all
  end

  # GET /apartamentos/1
  # GET /apartamentos/1.json
  def show
  end

  # GET /apartamentos/new
  def new
    @apartamento = Apartamento.new
  end

  # GET /apartamentos/1/edit
  def edit
  end

  # POST /apartamentos
  # POST /apartamentos.json
  def create
    @apartamento = Apartamento.new(apartamento_params)

    respond_to do |format|
      if @apartamento.save
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully created.' }
        format.json { render :show, status: :created, location: @apartamento }
      else
        format.html { render :new }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartamentos/1
  # PATCH/PUT /apartamentos/1.json
  def update
    respond_to do |format|
      if @apartamento.update(apartamento_params)
        format.html { redirect_to @apartamento, notice: 'Apartamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartamento }
      else
        format.html { render :edit }
        format.json { render json: @apartamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartamentos/1
  # DELETE /apartamentos/1.json
  def destroy
    @apartamento.destroy
    respond_to do |format|
      format.html { redirect_to apartamentos_url, notice: 'Apartamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartamento
      @apartamento = Apartamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartamento_params
      params.require(:apartamento).permit(:nombre, :torre, :piso)
    end
end

jueves/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

jueves/app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :identificacion, :apto)
    end
end

jueves/app/controllers/torres_controller.rb
class TorresController < ApplicationController
  before_action :set_torre, only: [:show, :edit, :update, :destroy]

  # GET /torres
  # GET /torres.json
  def index
    @torres = Torre.all
  end

  # GET /torres/1
  # GET /torres/1.json
  def show
  end

  # GET /torres/new
  def new
    @torre = Torre.new
  end

  # GET /torres/1/edit
  def edit
  end

  # POST /torres
  # POST /torres.json
  def create
    @torre = Torre.new(torre_params)

    respond_to do |format|
      if @torre.save
        format.html { redirect_to @torre, notice: 'Torre was successfully created.' }
        format.json { render :show, status: :created, location: @torre }
      else
        format.html { render :new }
        format.json { render json: @torre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /torres/1
  # PATCH/PUT /torres/1.json
  def update
    respond_to do |format|
      if @torre.update(torre_params)
        format.html { redirect_to @torre, notice: 'Torre was successfully updated.' }
        format.json { render :show, status: :ok, location: @torre }
      else
        format.html { render :edit }
        format.json { render json: @torre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /torres/1
  # DELETE /torres/1.json
  def destroy
    @torre.destroy
    respond_to do |format|
      format.html { redirect_to torres_url, notice: 'Torre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_torre
      @torre = Torre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def torre_params
      params.require(:torre).permit(:nombre, :portero)
    end
end

jueves/app/helpers/apartamentos_helper.rb
module ApartamentosHelper
end

jueves/app/helpers/application_helper.rb
module ApplicationHelper
end

jueves/app/helpers/personas_helper.rb
module PersonasHelper
end

jueves/app/helpers/torres_helper.rb
module TorresHelper
end

jueves/app/views/apartamentos/_form.html.erb
<%= form_for(apartamento) do |f| %>
  <% if apartamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartamento.errors.count, "error") %> prohibited this apartamento from being saved:</h2>

      <ul>
      <% apartamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :torre %>
    <%= f.text_field :torre %>
  </div>

  <div class="field">
    <%= f.label :piso %>
    <%= f.text_field :piso %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jueves/app/views/apartamentos/edit.html.erb
<h1>Editing Apartamento</h1>

<%= render 'form', apartamento: @apartamento %>

<%= link_to 'Show', @apartamento %> |
<%= link_to 'Back', apartamentos_path %>

jueves/app/views/apartamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Torre</th>
      <th>Piso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartamentos.each do |apartamento| %>
      <tr>
        <td><%= apartamento.nombre %></td>
        <td><%= apartamento.torre %></td>
        <td><%= apartamento.piso %></td>
        <td><%= link_to 'Show', apartamento %></td>
        <td><%= link_to 'Edit', edit_apartamento_path(apartamento) %></td>
        <td><%= link_to 'Destroy', apartamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartamento', new_apartamento_path %>

jueves/app/views/apartamentos/new.html.erb
<h1>New Apartamento</h1>

<%= render 'form', apartamento: @apartamento %>

<%= link_to 'Back', apartamentos_path %>

jueves/app/views/apartamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @apartamento.nombre %>
</p>

<p>
  <strong>Torre:</strong>
  <%= @apartamento.torre %>
</p>

<p>
  <strong>Piso:</strong>
  <%= @apartamento.piso %>
</p>

<%= link_to 'Edit', edit_apartamento_path(@apartamento) %> |
<%= link_to 'Back', apartamentos_path %>

jueves/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jueves</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

jueves/app/views/personas/_form.html.erb
<%= form_for(persona) do |f| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :identificacion %>
    <%= f.text_field :identificacion %>
  </div>

  <div class="field">
    <%= f.label :apto %>
    <%= f.text_field :apto %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jueves/app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

jueves/app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Identificacion</th>
      <th>Apto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.identificacion %></td>
        <td><%= persona.apto %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

jueves/app/views/personas/new.html.erb
<h1>New Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to 'Back', personas_path %>

jueves/app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Identificacion:</strong>
  <%= @persona.identificacion %>
</p>

<p>
  <strong>Apto:</strong>
  <%= @persona.apto %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>

jueves/app/views/torres/_form.html.erb
<%= form_for(torre) do |f| %>
  <% if torre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(torre.errors.count, "error") %> prohibited this torre from being saved:</h2>

      <ul>
      <% torre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :portero %>
    <%= f.text_field :portero %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

jueves/app/views/torres/edit.html.erb
<h1>Editing Torre</h1>

<%= render 'form', torre: @torre %>

<%= link_to 'Show', @torre %> |
<%= link_to 'Back', torres_path %>

jueves/app/views/torres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Torres</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Portero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @torres.each do |torre| %>
      <tr>
        <td><%= torre.nombre %></td>
        <td><%= torre.portero %></td>
        <td><%= link_to 'Show', torre %></td>
        <td><%= link_to 'Edit', edit_torre_path(torre) %></td>
        <td><%= link_to 'Destroy', torre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Torre', new_torre_path %>

jueves/app/views/torres/new.html.erb
<h1>New Torre</h1>

<%= render 'form', torre: @torre %>

<%= link_to 'Back', torres_path %>

jueves/app/views/torres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @torre.nombre %>
</p>

<p>
  <strong>Portero:</strong>
  <%= @torre.portero %>
</p>

<%= link_to 'Edit', edit_torre_path(@torre) %> |
<%= link_to 'Back', torres_path %>